import { motion as Motion } from "framer-motion";
import { Activity, ArrowRight, Brain, Cpu, Leaf } from "lucide-react";
import { Link } from "react-router-dom";

const featureCards = [
  {
    title: "Live Telemetry",
    description: "Track CPU, memory, thermal, and network behavior with second-by-second refresh.",
    icon: Activity,
  },
  {
    title: "LSTM Intelligence",
    description: "Receive predictive optimization suggestions generated by your resource model.",
    icon: Brain,
  },
  {
    title: "Energy Focus",
    description: "Highlight power-heavy patterns early and act before system efficiency drops.",
    icon: Leaf,
  },
];

const stats = [
  { label: "Avg. Power Saved", value: "18%" },
  { label: "Sampling Rate", value: "1s" },
  { label: "Insight Latency", value: "< 300ms" },
];

const gridStyle = {
  backgroundImage:
    "radial-gradient(circle at 20% 20%, rgba(67, 232, 145, 0.2), transparent 38%), radial-gradient(circle at 80% 10%, rgba(94, 255, 171, 0.14), transparent 34%), linear-gradient(rgba(84, 255, 170, 0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(84, 255, 170, 0.08) 1px, transparent 1px)",
  backgroundSize: "auto, auto, 2.2rem 2.2rem, 2.2rem 2.2rem",
};

const Home = () => {
  return (
    <main className="relative min-h-screen overflow-hidden bg-gradient-to-br from-[#03150d] to-[#082417] px-5 pb-16 pt-10 text-emerald-100">
      <div className="pointer-events-none absolute inset-0" style={gridStyle} aria-hidden="true" />

      <section className="relative z-10 mx-auto w-full max-w-6xl pt-10 text-center">
        <Motion.p
          className="mx-auto mb-5 inline-flex w-fit items-center gap-2 rounded-full border border-emerald-300/25 bg-emerald-900/45 px-3 py-1 text-xs uppercase tracking-wider text-emerald-200"
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          <Cpu size={16} />
          Resource Intelligence Control Plane
        </Motion.p>

        <Motion.h1
          className="mx-auto max-w-4xl text-4xl font-semibold leading-tight text-emerald-50 sm:text-5xl lg:text-6xl"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          Monitor. Predict. Optimize.
        </Motion.h1>

        <Motion.p
          className="mx-auto mt-4 max-w-2xl text-base text-emerald-200/70"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          Launch your green operations dashboard to monitor resource behavior in real time and get
          LSTM-powered optimization recommendations instantly.
        </Motion.p>

        <Motion.div
          className="mt-7 flex flex-wrap items-center justify-center gap-3"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
        >
          <Link
            className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-br from-emerald-200 to-emerald-400 px-5 py-3 font-semibold text-emerald-950 shadow-lg shadow-emerald-500/30 transition hover:-translate-y-0.5"
            to="/dashboard"
          >
            Open Dashboard
            <ArrowRight size={18} />
          </Link>
          <a
            className="inline-flex items-center rounded-xl border border-emerald-300/25 bg-emerald-900/40 px-5 py-3 font-semibold text-emerald-100 transition hover:-translate-y-0.5"
            href="#features"
          >
            Explore Features
          </a>
        </Motion.div>
      </section>

      <section className="relative z-10 mx-auto mt-6 grid w-full max-w-6xl gap-4 md:grid-cols-3" aria-label="System summary">
        {stats.map((entry, index) => (
          <Motion.article
            className="rounded-2xl border border-emerald-300/20 bg-gradient-to-br from-emerald-900/50 to-emerald-950/60 p-4 text-left"
            key={entry.label}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.35 + index * 0.08 }}
          >
            <h2 className="text-2xl font-semibold text-emerald-50">{entry.value}</h2>
            <p className="mt-1 text-sm text-emerald-200/70">{entry.label}</p>
          </Motion.article>
        ))}
      </section>

      <section className="relative z-10 mx-auto mt-5 grid w-full max-w-6xl gap-4 md:grid-cols-3" id="features">
        {featureCards.map((feature, index) => {
          const Icon = feature.icon;
          return (
            <Motion.article
              className="rounded-2xl border border-emerald-300/20 bg-gradient-to-br from-emerald-900/50 to-emerald-950/70 p-4"
              key={feature.title}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.4, delay: index * 0.07 }}
            >
              <span className="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-300/15 text-emerald-200" aria-hidden="true">
                <Icon size={20} />
              </span>
              <h3 className="mt-3 text-lg font-semibold text-emerald-50">{feature.title}</h3>
              <p className="mt-2 text-sm text-emerald-200/70">{feature.description}</p>
            </Motion.article>
          );
        })}
      </section>
    </main>
  );
};

export default Home;
