import { motion as Motion } from "framer-motion";
import { Activity, Brain, Leaf } from "lucide-react";
import Orb from "../../components/Orb/Orb";
import { NavLink } from "react-router-dom";
import ChromaGrid from "../../components/ChromaGrid/ChromaGrid";
import SameerProfile from "../../assets/sameer-profile.jpeg";
import SachitProfile from "../../assets/sachit-profile.jpeg";

const featureCards = [
  {
    title: "Live Telemetry",
    description:
      "Track CPU, memory, thermal, and network behavior with every 3 seconds refresh.",
    icon: Activity,
  },
  {
    title: "LSTM Intelligence",
    description:
      "Receive predictive optimization suggestions generated by your resource model.",
    icon: Brain,
  },
  {
    title: "Energy Focus",
    description:
      "Highlight power-heavy patterns early and act before system efficiency drops.",
    icon: Leaf,
  },
];

const stats = [
  { label: "Avg. Power Saved", value: "18%" },
  { label: "Sampling Rate", value: "3s" },
  { label: "Insight Latency", value: "< 300ms" },
];

const Home = () => {
  return (
    <main className="relative overflow-hidden bg-black px-5 pb-16 pt-10 text-white flex flex-col gap-50">
      <section className="relative z-10 w-full h-screen flex flex-col justify-center items-center gap-10 bg-black rounded-2xl">
        <div
          style={{
            width: "100%",
            height: "100%",
            position: "relative",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Orb
            hoverIntensity={2}
            rotateOnHover
            hue={0}
            forceHoverState={false}
            backgroundColor="#000000"
          />
          <div className="absolute inset-0 flex flex-col justify-center items-center z-20">
            <Motion.h1
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.35 }}
              className="text-5xl max-w-3xl font-bold  text-center"
            >
              AI Based Resource Optimization System using LSTM model
            </Motion.h1>
            <Motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.4 }}
              className="flex justify-center items-center gap-10"
            >
              <NavLink
                to="/dashboard"
                className="mt-8 inline-flex w-55 justify-center items-center gap-3 rounded-full bg-white px-6 py-3 text-lg font-semibold text-black transition "
              >
                Explore Dashboard
              </NavLink>
              <NavLink className="mt-8 inline-flex w-50 justify-center items-center gap-3 rounded-full bg-gray-900 px-6 py-3 text-lg border border-gray-600 font-semibold text-gray-600 transition ">
                Documentation
              </NavLink>
            </Motion.div>
          </div>
        </div>
      </section>
      <section className="flex flex-col items-center gap-10 justify-center w-full">
        <div className="flex justify-center gap-10 w-full max-w-7xl">
          {stats.map((entry, index) => (
            <Motion.article
              className="rounded-2xl flex-1   p-4 text-left bg-white/10 backdrop-blur-md"
              key={entry.label}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.35 + index * 0.08 }}
            >
              <h2 className="text-2xl font-semibold text-emerald-50">
                {entry.value}
              </h2>
              <p className="mt-1 text-sm ">{entry.label}</p>
            </Motion.article>
          ))}
        </div>
        <div className="flex justify-center gap-10 w-full max-w-7xl">
          {featureCards.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Motion.article
                className="rounded-2xl flex-1  bg-white/10 backdrop-blur-md p-4"
                key={feature.title}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.2 }}
                transition={{ duration: 0.4, delay: index * 0.07 }}
              >
                <span
                  className="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-300/15 "
                  aria-hidden="true"
                >
                  <Icon size={20} />
                </span>
                <h3 className="mt-3 text-lg font-semibold ">{feature.title}</h3>
                <p className="mt-2 text-sm ">{feature.description}</p>
              </Motion.article>
            );
          })}
        </div>
      </section>
    </main>
  );
};

export default Home;
